"""Synthetic DEMO market data.

This provider exists so the project can be run, tested and demonstrated without an API key.
Prices are generated from a seeded regime-switching random walk - they are NOT market data and
do not resemble the real prices of the companies named. Every API response carries
``source: "demo"`` and the UI shows a permanent "Demo data" banner.

Output is deterministic per ticker (seeded by a CRC of the symbol) except that the series
ends on the most recent weekday.
"""
from __future__ import annotations

import zlib
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

import numpy as np
import pandas as pd

from app.services.market.types import Quote, SymbolMatch
from app.utils.errors import SymbolNotFoundError

DAILY_BARS = 1500
SESSION_OPEN_UTC = (14, 30)  # 09:30 US Eastern (standard time) - an approximation for demo bars
SESSION_MINUTES = 390


@dataclass(frozen=True)
class DemoCompany:
    ticker: str
    name: str
    exchange: str
    price: float  # price of the final synthetic bar
    vol_scale: float = 1.0
    avg_volume: float = 20_000_000
    kind: str = "Common Stock"


_C = DemoCompany
DEMO_COMPANIES: dict[str, DemoCompany] = {c.ticker: c for c in [
    _C("AAPL", "Apple Inc.", "NASDAQ", 214.3, 0.9, 55e6),
    _C("MSFT", "Microsoft Corporation", "NASDAQ", 428.7, 0.85, 22e6),
    _C("NVDA", "NVIDIA Corporation", "NASDAQ", 131.4, 1.6, 210e6),
    _C("TSLA", "Tesla, Inc.", "NASDAQ", 246.9, 1.9, 95e6),
    _C("AMZN", "Amazon.com, Inc.", "NASDAQ", 187.2, 1.1, 42e6),
    _C("GOOGL", "Alphabet Inc. Class A", "NASDAQ", 171.8, 1.0, 28e6),
    _C("META", "Meta Platforms, Inc.", "NASDAQ", 512.6, 1.3, 14e6),
    _C("JPM", "JPMorgan Chase & Co.", "NYSE", 198.4, 0.8, 9e6),
    _C("V", "Visa Inc.", "NYSE", 276.5, 0.75, 6e6),
    _C("JNJ", "Johnson & Johnson", "NYSE", 158.2, 0.6, 7e6),
    _C("WMT", "Walmart Inc.", "NYSE", 68.9, 0.65, 18e6),
    _C("XOM", "Exxon Mobil Corporation", "NYSE", 114.7, 0.95, 16e6),
    _C("KO", "The Coca-Cola Company", "NYSE", 63.4, 0.55, 14e6),
    _C("DIS", "The Walt Disney Company", "NYSE", 97.3, 1.15, 10e6),
    _C("NFLX", "Netflix, Inc.", "NASDAQ", 641.2, 1.4, 4e6),
    _C("AMD", "Advanced Micro Devices, Inc.", "NASDAQ", 158.6, 1.6, 55e6),
    _C("INTC", "Intel Corporation", "NASDAQ", 31.2, 1.3, 45e6),
    _C("BA", "The Boeing Company", "NYSE", 182.5, 1.3, 7e6),
    _C("PFE", "Pfizer Inc.", "NYSE", 28.9, 0.8, 30e6),
    _C("COST", "Costco Wholesale Corporation", "NASDAQ", 846.3, 0.8, 2e6),
    _C("SPY", "SPDR S&P 500 ETF Trust", "NYSE Arca", 548.1, 0.55, 65e6, "ETF"),
    _C("QQQ", "Invesco QQQ Trust", "NASDAQ", 471.9, 0.7, 40e6, "ETF"),
    _C("DIA", "SPDR Dow Jones Industrial Average ETF", "NYSE Arca", 402.7, 0.5, 3e6, "ETF"),
    _C("IWM", "iShares Russell 2000 ETF", "NYSE Arca", 207.6, 0.85, 28e6, "ETF"),
]}

# (drift per day, daily sigma) for bull / bear / sideways regimes
_REGIMES = np.array([[0.0009, 0.0105], [-0.0009, 0.0190], [0.0001, 0.0080]])
_STAY = 0.985


def _last_weekday(now: datetime) -> pd.Timestamp:
    d = pd.Timestamp(now.date())
    while d.weekday() >= 5:
        d -= pd.Timedelta(days=1)
    return d.tz_localize("UTC")


def _is_market_open(now: datetime) -> bool:
    if now.weekday() >= 5:
        return False
    start = now.replace(hour=SESSION_OPEN_UTC[0], minute=SESSION_OPEN_UTC[1], second=0, microsecond=0)
    return start <= now < start + timedelta(minutes=SESSION_MINUTES)


class DemoProvider:
    name = "demo"
    label = "Demo data"
    data_note = (
        "DEMO DATA: prices are synthetic, generated by a seeded random walk. They are not real "
        "market data and must not be used for any financial decision."
    )

    def __init__(self) -> None:
        self._daily_cache: dict[str, pd.DataFrame] = {}

    # --------------------------------------------------------------- search --
    def search(self, query: str) -> list[SymbolMatch]:
        q = query.strip().lower()
        hits = [
            c for c in DEMO_COMPANIES.values() if q in c.ticker.lower() or q in c.name.lower()
        ]
        hits.sort(key=lambda c: (not c.ticker.lower().startswith(q), c.ticker.lower() != q, c.ticker))
        return [
            SymbolMatch(c.ticker, c.name, c.exchange, "United States", c.kind, "USD") for c in hits[:12]
        ]

    # ---------------------------------------------------------------- daily --
    def _daily(self, ticker: str) -> pd.DataFrame:
        company = DEMO_COMPANIES.get(ticker)
        if company is None:
            raise SymbolNotFoundError(f"'{ticker}' is not part of the demo universe.")
        end = _last_weekday(datetime.now(timezone.utc))
        cache_key = f"{ticker}:{end.date()}"
        if cache_key in self._daily_cache:
            return self._daily_cache[cache_key]

        rng = np.random.default_rng(zlib.crc32(ticker.encode()))
        n = DAILY_BARS
        dates = pd.bdate_range(end=end.tz_localize(None), periods=n).tz_localize("UTC")

        state = int(rng.integers(0, 3))
        states = np.empty(n, dtype=int)
        for i in range(n):
            if rng.random() > _STAY:
                state = int(rng.choice([s for s in range(3) if s != state]))
            states[i] = state
        mu, sigma = _REGIMES[states, 0], _REGIMES[states, 1] * company.vol_scale
        rets = rng.normal(mu, sigma)
        jumps = rng.random(n) < 0.012
        rets[jumps] += rng.choice([-1, 1], jumps.sum()) * sigma[jumps] * rng.uniform(3.0, 5.0, jumps.sum())

        path = np.exp(np.cumsum(rets))
        close = path * (company.price / path[-1])
        prev = np.concatenate([[close[0] / (1 + rets[0])], close[:-1]])
        open_ = prev * (1 + rng.normal(0, 0.0025, n))
        span = np.abs(rng.normal(0, 0.45 * sigma + 0.002))
        high = np.maximum(open_, close) * (1 + span)
        low = np.minimum(open_, close) * (1 - span)
        activity = 1 + 7 * np.abs(rets) / 0.012
        volume = company.avg_volume * rng.lognormal(0, 0.22, n) * activity / activity.mean()
        spikes = rng.random(n) < 0.012
        volume[spikes] *= rng.uniform(2.5, 4.5, spikes.sum())

        df = pd.DataFrame(
            {"open": open_, "high": high, "low": low, "close": close, "volume": volume.round()},
            index=pd.DatetimeIndex(dates, name="t"),
        )
        # replace any older (previous-day) frame for this ticker, keep the rest
        for k in [k for k in self._daily_cache if k.startswith(f"{ticker}:")]:
            self._daily_cache.pop(k, None)
        self._daily_cache[cache_key] = df
        return df

    # ------------------------------------------------------------ intraday ---
    def _intraday(self, ticker: str, step_minutes: int, sessions: int) -> pd.DataFrame:
        daily = self._daily(ticker).iloc[-sessions:]
        frames = []
        steps = SESSION_MINUTES // step_minutes
        for day, row in daily.iterrows():
            rng = np.random.default_rng(zlib.crc32(f"{ticker}{day.date()}{step_minutes}".encode()))
            noise = rng.normal(0, 1, steps).cumsum()
            ramp = np.linspace(0, 1, steps)
            bridge = noise - ramp * noise[-1]  # Brownian bridge: starts and ends at 0
            amp = max(row["high"] - row["low"], 1e-6) * 0.5 / max(np.abs(bridge).max(), 1e-6)
            path = row["open"] + (row["close"] - row["open"]) * ramp + bridge * amp
            path = np.clip(path, row["low"], row["high"])
            path[0], path[-1] = row["open"], row["close"]
            opens = np.concatenate([[row["open"]], path[:-1]])
            wiggle = np.abs(rng.normal(0, 0.0006, steps)) * path
            weights = 1 + 1.6 * (np.abs(ramp - 0.5) * 2) ** 2  # U-shaped intraday volume
            vol = row["volume"] * weights / weights.sum()
            start = day + pd.Timedelta(hours=SESSION_OPEN_UTC[0], minutes=SESSION_OPEN_UTC[1])
            idx = pd.DatetimeIndex([start + pd.Timedelta(minutes=step_minutes * i) for i in range(steps)], name="t")
            frames.append(pd.DataFrame({
                "open": opens,
                "high": np.minimum(np.maximum(opens, path) + wiggle, row["high"]),
                "low": np.maximum(np.minimum(opens, path) - wiggle, row["low"]),
                "close": path,
                "volume": vol.round(),
            }, index=idx))
        out = pd.concat(frames)
        now = pd.Timestamp.now(tz="UTC")
        return out[out.index <= now]  # never emit bars from the future

    def time_series(self, ticker: str, interval: str, outputsize: int) -> pd.DataFrame:
        if interval == "1day":
            return self._daily(ticker).iloc[-outputsize:]
        if interval == "5min":
            return self._intraday(ticker, 5, 1).iloc[-outputsize:]
        if interval == "30min":
            return self._intraday(ticker, 30, 5).iloc[-outputsize:]
        raise ValueError(f"Unsupported demo interval {interval}")

    # --------------------------------------------------------------- quotes --
    def quotes(self, tickers: list[str]) -> dict[str, Quote]:
        now = datetime.now(timezone.utc)
        out: dict[str, Quote] = {}
        for t in tickers:
            company = DEMO_COMPANIES.get(t)
            if company is None:
                continue
            df = self._daily(t)
            last, prev = df.iloc[-1], df.iloc[-2]
            price = float(last["close"])
            prev_close = float(prev["close"])
            out[t] = Quote(
                ticker=t, name=company.name, exchange=company.exchange, currency="USD",
                price=round(price, 2), change=round(price - prev_close, 2),
                change_percent=round((price / prev_close - 1) * 100, 2),
                previous_close=round(prev_close, 2), open=round(float(last["open"]), 2),
                high=round(float(last["high"]), 2), low=round(float(last["low"]), 2),
                volume=int(last["volume"]), average_volume=int(df["volume"].iloc[-50:].mean()),
                is_market_open=_is_market_open(now), as_of=now,
                fifty_two_week_low=round(float(df["low"].iloc[-252:].min()), 2),
                fifty_two_week_high=round(float(df["high"].iloc[-252:].max()), 2),
            )
        return out
